# Generated by Django 4.0.4 on 2022-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('modelID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentID', models.CharField(max_length=500)),
                ('SubjectID', models.CharField(default='ไม่มีข้อมูล', max_length=500)),
                ('Grade', models.CharField(default='ไม่มีข้อมูล', max_length=5)),
                ('Semester', models.CharField(default='ไม่มีข้อมูล', max_length=5)),
                ('Year', models.CharField(default='ไม่มีข้อมูล', max_length=10)),
                ('Curriculum', models.CharField(default='ไม่มีข้อมูล', max_length=500)),
            ],
        ),
    ]
